# k8s/databases/auth-database-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: auth-database
  namespace: auth
spec:
  selector:
    app: auth-database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
