# k8s/databases/backend-database-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-database
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-database
  template:
    metadata:
      labels:
        app: backend-database
    spec:
      containers:
      - name: backend-database
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: "${DB_NAME}"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: backend-db-credentials
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-db-credentials
              key: password
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
