# k8s/backend/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: backend:latest
        ports:
        - containerPort: 8082
        env:
        - name: SERVER_PORT
          value: "8082"
        - name: DB_URL
          value: "jdbc:mysql://backend-database:3306/${DB_NAME}"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: backend-db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-db-credentials
              key: password
