networks:
  server:
  client:
    driver: bridge

volumes:
  database_data:
  auth_data:

services:
  frontend:
    image: ${DOCKER_USERNAME}/${DOCKER_REPO}-frontend
    container_name: frontend
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    networks:
      - client
    depends_on:
      - auth
      - backend
    restart: always

  auth:
    image: ${DOCKER_USERNAME}/${DOCKER_REPO}-auth
    container_name: auth
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - DB_URL=jdbc:mysql://auth_database:${DB_PORT}/${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - server
      - client
    depends_on:
      - auth_database
    restart: always

  backend:
    image: ${DOCKER_USERNAME}/${DOCKER_REPO}-backend
    container_name: backend
    ports:
      - 8082:8082
    environment:
      - SERVER_PORT=8082
      - DB_URL=jdbc:mysql://backend_database:${DB_PORT}/${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - server
      - client
    depends_on:
      - backend_database
    restart: always

  backend_database:
    image: ${DOCKER_USERNAME}/${DOCKER_REPO}-database
    container_name: backend_database
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - server
    restart: always
    
  auth_database:
    image: ${DOCKER_USERNAME}/${DOCKER_REPO}-database
    container_name: auth_database
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - auth_data:/var/lib/mysql
    networks:
      - server
    restart: always

  adminer_backend:
    image: adminer:latest
    container_name: adminer_backend
    ports:
      - "8087:8080"
    depends_on:
      - backend_database
    environment:
      - ADMINER_DEFAULT_SERVER=backend_database
      - ADMINER_PORT=${DB_PORT}
      - ADMINER_DEFAULT_USERNAME=${DB_USERNAME}
      - ADMINER_DEFAULT_PASSWORD=${DB_PASSWORD}
      - ADMINER_DEFAULT_DATABASE=${DB_NAME}
    networks:
      - client
      - server
    restart: always

  adminer_auth:
    image: adminer:latest
    container_name: adminer_auth
    ports:
      - "8088:8080"
    depends_on:
      - auth_database
    environment:
      - ADMINER_DEFAULT_SERVER=auth_database
      - ADMINER_PORT=${DB_PORT}
      - ADMINER_DEFAULT_USERNAME=${DB_USERNAME}
      - ADMINER_DEFAULT_PASSWORD=${DB_PASSWORD}
      - ADMINER_DEFAULT_DATABASE=${DB_NAME}
    networks:
      - client
      - server
    restart: always